name: Windows
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          rake msi:build
      - uses: actions/upload-artifact@master
        with:
          name: packages-windows-x86_64
          path: td-agent/msi/repositories
